demo:
  hogeApiConfig:
    url: http://localhost/hoge
    connectionTimeout: 100ms
    readTimeout: 400ms
  fugaApiConfig:
    url: http://localhost/fuga
    connectionTimeout: 100ms
    readTimeout: 400ms
