plugins {
	id 'java'
}

group = 'com.github.massakai.tutorials.springframework'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
	sourceCompatibility = JavaVersion.VERSION_11
	targetCompatibility = JavaVersion.VERSION_11
}

repositories {
	mavenCentral()
}

def springBootVersion = '2.4.4'

dependencies {
	annotationProcessor platform("org.springframework.boot:spring-boot-dependencies:${springBootVersion}")
	implementation platform("org.springframework.boot:spring-boot-dependencies:${springBootVersion}")
	testImplementation platform("org.springframework.boot:spring-boot-dependencies:${springBootVersion}")

	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
	implementation 'org.springframework.boot:spring-boot-starter'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(Test).configureEach {
	useJUnitPlatform()
}
